.TH ooplss 1 
.SH NAME
ooplss \- Object oriented programming language with subtyping and subclassing

.SH SYNOPSIS

.B ooplss 
[\-h] [\-o \fIdirectory\fP] [\-f \fPfile\fP]

.SH DESCRIPTION

\fBooplss\fP translates ooplss source code into a Java class file. It either reads 
from the standard input or from the specified \fIfile\fP.

.SH OPTIONS
.TP
\-h 
Show the help

.TP
\-o \fIdirectory\fP
Specify the output directory of the translated class file

.TP
\-f \fIfile\fP
Specify the input file to translate

.SH AUTHORS

Ruben Baer <ruben.baer@codedump.ch>
.PP 
Stefan Heinemann <stefan.heinemann@codedump.ch>

