#!/bin/bash

if [[ -f ooplss.jar ]]; then 
	java -cp lib/:/usr/share/ooplss/lib/ -jar ooplss.jar $1 $2 $3 $4 $5 $6 $7 $8 $9
else
	# calling from somewhere
	java -cp lib/:/usr/share/ooplss/lib/ -jar /usr/share/ooplss/ooplss.jar $1 $2 $3 $4 $5 $6 $7 $8 $9
fi


