.TH OOPLSS 1
.SH NAME
ooplss \- Object\-Oriented Programming Language with Subtyping and Subclassing

.SH SYNOPSIS

.B ooplss
[\-h] [\-o \fIdirectory\fP] [\-f \fPfile\fP] [\-n] [\-k]

.SH DESCRIPTION

\fBooplss\fP translates ooplss source code into a Java class file. It either reads
from the standard input or from the specified \fIfile\fP. If no output \fIdirectory\fP
was specified, the code is translated only to Java and then printed to the standard
output, otherwise a file called App.class is created in the output \fIdirectory\fP
containing the translated bytecode. If the output \fIdirectory\fP is specified and
the \-n option is present, the code is also translated to Java only, but written
into the file App.java in the output \fIdirectory\fP.

Note that for \fBooplss\fP to work either the classpath has to be set correctly
to find antlr3.jar and commons-cli-1.2.jar or it has to be run in the same
working directory as the lib/ folder (which contains those two jar packages).

.SH OPTIONS
.TP
\-h, \-\-help
Show the help

.TP
\-o, \-\-output=\fIdirectory\fP
Specify the output directory of the translated class file

.TP
\-f, \-\-file=\fIfile\fP
Specify the input file to translate

.TP
\-n, \-\-no\-translation
Translate only to Java

.TP
\-k, \-\-keep-java
Do not delete the temporary Java output file

.SH AUTHORS

Ruben Baer <ruben.baer@codedump.ch>
.PP
Stefan Heinemann <stefan.heinemann@codedump.ch>

.SH SEE ALSO

For further information visit http://ooplss.codedump.ch or
http://www.github.com/rubenbaer/ooplss.
